services:
  db:
    container_name: db
    build:
      context: ./db
      args:
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
    ports:
      - "${DB_PORT}"
    networks:
      - db-network
    volumes:
      - ./db/db-data:/var/lib/mysql

  backend:
    container_name: backend
    build: ./backend 
    env_file:
      - .env
    environment:
      - WEB_URL="${WEB_SCHEME_PROD}://${WEB_DOMAIN_PROD}:${WEB_PORT_PROD}"
    ports:
      - "${BACK_PORT}"
    networks:
      - air-in-network
      - db-network
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod-web
      args:
        WEB_BACK_URL: "${WEB_SCHEME_PROD}://${WEB_DOMAIN_PROD}:${WEB_PORT_PROD}${WEB_BACK_PATH}"
    env_file:
      - .env
    environment:
      - WEB_PORT=${WEB_PORT_PROD}
      - WEB_DOMAIN=${WEB_DOMAIN_PROD}
      - FRONT_URL="http://frontend:${FRONT_PORT}/"
      - BACK_URL="http://backend:${BACK_PORT}/"
    ports:
      - "${WEB_PORT_PROD}:${WEB_PORT_PROD}"
    networks:
      - air-in-network


networks:
  air-in-network:
    driver: bridge
  db-network:
    driver: bridge
