version: '1.0'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    env_file:
      - .env
    environment:
      - WEB_BACK_URL=${WEB_SCHEME_DEV}://${WEB_DOMAIN_DEV}${WEB_BACK_PATH}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    networks:
      - air-in-network
    depends_on:
      - backend
  
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    environment:
      - WEB_URL=${WEB_SCHEME_DEV}://${WEB_DOMAIN_DEV}
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    networks:
      - air-in-network
    depends_on:
      - db

  db:
    container_name: db
    build: ./db
    env_file:
      - .env
    networks:
      - air-in-network
  
  web:
    container_name: web
    build: ./web
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    environment:
      - WEB_PORT=${WEB_PORT_DEV}
      - WEB_DOMAIN=${WEB_DOMAIN_DEV}
      - FRONT_URL="${FRONT_SCHEME}://${FRONT_DOMAIN}:${FRONT_PORT}/"
      - BACK_URL="${BACK_SCHEME}://${BACK_DOMAIN}:${BACK_PORT}/"
    ports:
      - "${WEB_PORT_DEV}:${WEB_PORT_DEV}"
    networks:
      - air-in-network

networks:
  air-in-network:
    driver: bridge
