
services:
  db:
    container_name: db
    build: ./db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - db-network

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - WEB_BACK_URL=${WEB_SCHEME_DEV}://${WEB_DOMAIN_DEV}:${WEB_PORT_DEV}${WEB_BACK_PATH}
    ports:
      - "4200:4200"
    networks:
      - air-in-network
    depends_on:
      - backend
  
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    environment:
      - WEB_URL="${WEB_SCHEME_DEV}://${WEB_DOMAIN_DEV}:${WEB_PORT_DEV}"
    ports:
      - "1111:1111"
    networks:
      - air-in-network
      - db-network
    depends_on:
      - db
  
  web:
    container_name: web
    build: ./web
    env_file:
      - .env
    environment:
      - WEB_PORT=${WEB_PORT_DEV}
      - WEB_DOMAIN=${WEB_DOMAIN_DEV}
    ports:
      - "${WEB_PORT_DEV}:${WEB_PORT_DEV}"
    networks:
      - air-in-network
    depends_on:
      - frontend

networks:
  air-in-network:
    driver: bridge
  db-network:
    driver: bridge